configure: fix sanitizers' test program to mend ASan detection
Commit 218bb57 ("build-sys: check static linking of UBSAN", 2018-02-13)
adds a small test program to check whether ubsan works even when
configuring with --static. This added program is used to
detect all sanitizers, which breaks ASan's detection since the
compilation fails with -fsanitize=address, at least with gcc 5.4.0
and 7.2.0:

  qemu-conf.c: In function ‘main’:
  qemu-conf.c:3:20: error: integer overflow in expression [-Werror=overflow]
     return INT32_MIN / -1;
                      ^
  cc1: all warnings being treated as errors

Fix it by:

- Changing the test program to one that incurs undefined behaviour that isn't
  detected at compile-time, even with -fsanitize=address.

- To be extra safe (since compilers might evolve and eventually figure out
  the UB at compile-time), use this newly-added test only when checking
  for UBSan; use the skeleton otherwise.

Signed-off-by: Emilio G. Cota <cota@braap.org>